spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/event_analytics
  security:
    user:
      name: user
      password: password

app:
  security:
    jwt:
      secret: your-secret-key-should-be-at-least-32-characters-long
      expiration-ms: 86400000 # 1 giorno

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG